version: 2
runtime: php-8.3
node:
  version: 18
hooks:
  build:
    - npm install
    - npm run build
  start:
    - php artisan serve --port=8080 --host=0.0.0.0
env:
  - APP_ENV=production
  - APP_DEBUG=false
  - APP_URL=https://stay-ahead-p8i3iwwke-vikzdimensions-projects.vercel.app/
  - DB_CONNECTION=mysql
  - DB_HOST=your-db-host
  - DB_PORT=3306
  - DB_DATABASE=your-db-name
  - DB_USERNAME=your-db-username
  - DB_PASSWORD=your-db-password
